# Generated by Django 4.0.4 on 2022-04-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='aula',
        ),
        migrations.AddField(
            model_name='aluno',
            name='aula',
            field=models.ManyToManyField(to='escola.aula'),
        ),
    ]
