# Generated by Django 4.0.4 on 2022-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_remove_aula_aula_aluno_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='aula',
        ),
        migrations.AddField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(related_name='materias', to='escola.aluno'),
        ),
    ]
