# Generated by Django 4.0.4 on 2022-04-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_remove_aluno_aula_aula_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='aula',
            field=models.ManyToManyField(to='escola.aula'),
        ),
    ]
