# Generated by Django 4.0.4 on 2022-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_remove_aula_alunos_aluno_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='aluno',
            field=models.ManyToManyField(related_name='aulas', to='escola.aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aula',
            field=models.ManyToManyField(related_name='aulas', to='escola.aula'),
        ),
    ]
